development:
  adapter: postgresql
  encoding: unicode
  database: luckee_reports
  pool: 5
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: luckee_reports
  pool: 5
  host: localhost