development:
  adapter: postgresql
  encoding: unicode
  database: luckee_reports
  pool: 5
  host: localhost

production:
  url:  <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DB_POOL"] || ENV['MAX_THREADS'] || 1 %>